// <auto-generated />
using System;
using MES.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MES.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(MesDbContext))]
    [Migration("20260709025758_InitialPostgres")]
    partial class InitialPostgres
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MES.Domain.Entities.AlarmEvent", b =>
                {
                    b.Property<string>("AlarmCode")
                        .HasColumnType("text")
                        .HasColumnName("alarm_code");

                    b.Property<double?>("LowerLimit")
                        .HasColumnType("double precision")
                        .HasColumnName("lower_limit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<string>("MetricName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("metric_name");

                    b.Property<double>("MetricValue")
                        .HasColumnType("double precision")
                        .HasColumnName("metric_value");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("severity");

                    b.Property<string>("Sn")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sn");

                    b.Property<string>("StationCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("station_code");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<double?>("UpperLimit")
                        .HasColumnType("double precision")
                        .HasColumnName("upper_limit");

                    b.HasKey("AlarmCode");

                    b.HasIndex("StationCode", "OccurredAt");

                    b.ToTable("alarm_events", (string)null);
                });

            modelBuilder.Entity("MES.Domain.Entities.RouteStep", b =>
                {
                    b.Property<string>("FlowCode")
                        .HasColumnType("text")
                        .HasColumnName("flow_code");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer")
                        .HasColumnName("sequence");

                    b.Property<bool>("AllowRework")
                        .HasColumnType("boolean")
                        .HasColumnName("allow_rework");

                    b.Property<string>("StationCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("station_code");

                    b.Property<string>("StepCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("step_code");

                    b.Property<string>("StepType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("step_type");

                    b.HasKey("FlowCode", "Sequence");

                    b.HasIndex("StationCode");

                    b.ToTable("route_steps", (string)null);
                });

            modelBuilder.Entity("MES.Domain.Entities.SerialUnit", b =>
                {
                    b.Property<string>("Sn")
                        .HasColumnType("text")
                        .HasColumnName("sn");

                    b.Property<int?>("CompletedStepSequence")
                        .HasColumnType("integer")
                        .HasColumnName("completed_step_sequence");

                    b.Property<string>("CurrentStationCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("current_station_code");

                    b.Property<bool?>("LastTestPassed")
                        .HasColumnType("boolean")
                        .HasColumnName("last_test_passed");

                    b.Property<int?>("PendingStepSequence")
                        .HasColumnType("integer")
                        .HasColumnName("pending_step_sequence");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("WorkOrderNo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("work_order_no");

                    b.HasKey("Sn");

                    b.HasIndex("WorkOrderNo");

                    b.ToTable("serial_units", (string)null);
                });

            modelBuilder.Entity("MES.Domain.Entities.SpcRule", b =>
                {
                    b.Property<string>("RuleCode")
                        .HasColumnType("text")
                        .HasColumnName("rule_code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<double?>("LowerLimit")
                        .HasColumnType("double precision")
                        .HasColumnName("lower_limit");

                    b.Property<string>("MetricName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("metric_name");

                    b.Property<string>("ProductCode")
                        .HasColumnType("text")
                        .HasColumnName("product_code");

                    b.Property<string>("StationCode")
                        .HasColumnType("text")
                        .HasColumnName("station_code");

                    b.Property<double?>("UpperLimit")
                        .HasColumnType("double precision")
                        .HasColumnName("upper_limit");

                    b.HasKey("RuleCode");

                    b.HasIndex("ProductCode", "StationCode", "MetricName");

                    b.ToTable("spc_rules", (string)null);
                });

            modelBuilder.Entity("MES.Domain.Entities.Station", b =>
                {
                    b.Property<string>("StationCode")
                        .HasColumnType("text")
                        .HasColumnName("station_code");

                    b.Property<bool>("IsTestStation")
                        .HasColumnType("boolean")
                        .HasColumnName("is_test_station");

                    b.Property<string>("LineCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("line_code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("StationCode");

                    b.ToTable("stations", (string)null);
                });

            modelBuilder.Entity("MES.Domain.Entities.TestFlow", b =>
                {
                    b.Property<string>("FlowCode")
                        .HasColumnType("text")
                        .HasColumnName("flow_code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("product_code");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("version");

                    b.HasKey("FlowCode");

                    b.HasIndex("ProductCode");

                    b.ToTable("test_flows", (string)null);
                });

            modelBuilder.Entity("MES.Domain.Entities.TestRecord", b =>
                {
                    b.Property<string>("Sn")
                        .HasColumnType("text")
                        .HasColumnName("sn");

                    b.Property<string>("StationCode")
                        .HasColumnType("text")
                        .HasColumnName("station_code");

                    b.Property<string>("TestBatchId")
                        .HasColumnType("text")
                        .HasColumnName("test_batch_id");

                    b.Property<string>("Metrics")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("metrics");

                    b.Property<bool>("Passed")
                        .HasColumnType("boolean")
                        .HasColumnName("passed");

                    b.Property<string>("RawPayload")
                        .HasColumnType("text")
                        .HasColumnName("raw_payload");

                    b.Property<DateTimeOffset>("TestedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("tested_at");

                    b.HasKey("Sn", "StationCode", "TestBatchId");

                    b.HasIndex("TestedAt");

                    b.HasIndex("Sn", "StationCode", "TestBatchId")
                        .IsUnique();

                    b.ToTable("test_records", (string)null);
                });

            modelBuilder.Entity("MES.Domain.Entities.TraceEvent", b =>
                {
                    b.Property<string>("Sn")
                        .HasColumnType("text")
                        .HasColumnName("sn");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("EventType")
                        .HasColumnType("text")
                        .HasColumnName("event_type");

                    b.Property<string>("StationCode")
                        .HasColumnType("text")
                        .HasColumnName("station_code");

                    b.Property<string>("OperatorId")
                        .HasColumnType("text")
                        .HasColumnName("operator_id");

                    b.Property<string>("Message")
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.HasKey("Sn", "OccurredAt", "EventType", "StationCode", "OperatorId");

                    b.HasIndex("Sn", "OccurredAt");

                    b.ToTable("trace_events", (string)null);
                });

            modelBuilder.Entity("MES.Domain.Entities.WorkOrder", b =>
                {
                    b.Property<string>("WorkOrderNo")
                        .HasColumnType("text")
                        .HasColumnName("work_order_no");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("PlannedQty")
                        .HasColumnType("integer")
                        .HasColumnName("planned_qty");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("product_code");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("TestFlowCode")
                        .HasColumnType("text")
                        .HasColumnName("test_flow_code");

                    b.HasKey("WorkOrderNo");

                    b.HasIndex("ProductCode");

                    b.ToTable("work_orders", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
